# Changes here will be overwritten by Copier
_commit: 080c9c2
_src_path: gh:browniebroke/pypackage-template
add_me_as_contributor: false
copyright_year: '2023'
documentation: false
email: nick@koston.org
full_name: J. Nick Koston
github_username: bdraco
initial_commit: true
open_source_license: Apache Software License 2.0
package_name: aiohttp_zlib_ng
project_name: aiohttp-zlib-ng
project_short_description: Enable zlib_ng on aiohttp
project_slug: aiohttp-zlib-ng
run_poetry_install: true
setup_github: true
setup_pre_commit: true

